language: node_js
node_js:
  - "0.10.x"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g karma
  - ./scripts/web-server.js > /dev/null &
  - sleep 1 # give server time to start

script: "grunt"